apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: trips
  name: trips
data:
  HTTP_PORT: "3000"
  AUTH_HOST: "auth"
  AUTH_PORT: "3001"
  POSTGRES_URL: "postgres://prisma:example@postgres:5432/diplomski?schema=public"