apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips
  name: trips
spec:
  selector:
    app: trips
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
