apiVersion: v1
kind: Service
metadata:
  labels:
    app: trips
  name: trips
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: trips
  type: NodePort
