apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chats
  name: chats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats
  template:
    metadata:
      labels:
        app: chats
    spec:
      containers:
        - image: europe-central2-docker.pkg.dev/diplomski-431623/chats/production
          name: chats
          env:
            - name: HTTP_PORT
              value: '3000'
          ports:
            - containerPort: 3000
