apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chats
  name: chats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chats
  template:
    metadata:
      labels:
        app: chats
    spec:
      containers:
        - name: chats
          image: europe-central2-docker.pkg.dev/diplomski-431623/chats/production
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: chats
          ports:
            - containerPort: 3000
