apiVersion: v1
kind: Service
metadata:
  labels:
    app: chats
  name: chats
spec:
  selector:
    app: chats
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
