name: diplomski-dev

include:
  - path:
      - docker-compose.base.yml

x-base-microservice-dev: &base-microservice-dev
  # watch: //TODO
  #   - action: sync
  #     path: ./
  #     target: /usr/src/app
  build:
    target: development
  volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules

services:
  api-gateway:
    image: us-east1-docker.pkg.dev/diplomski-431623/api-gateway/development
    <<: *base-microservice-dev

  auth:
    image: us-east1-docker.pkg.dev/diplomski-431623/auth/development
    <<: *base-microservice-dev

  users:
    image: us-east1-docker.pkg.dev/diplomski-431623/users/development
    <<: *base-microservice-dev

  locations:
    image: us-east1-docker.pkg.dev/diplomski-431623/locations/development
    <<: *base-microservice-dev

  trips:
    image: us-east1-docker.pkg.dev/diplomski-431623/trips/development
    <<: *base-microservice-dev

  files:
    image: us-east1-docker.pkg.dev/diplomski-431623/files/development
    <<: *base-microservice-dev

  chats:
    image: us-east1-docker.pkg.dev/diplomski-431623/chats/developments
    <<: *base-microservice-dev
