name: diplomski

include:
  - path:
      - docker-compose.base.yml

x-base-microservice: &base-microservice
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - '3000'
  restart: unless-stopped
  depends_on:
    - postgres
    - rabbitmq
  env_file:
    - .env

services:
  nginx:
    image: nginx:latest
    depends_on:
      - api-gateway
      - auth
      - users
      - locations
      - chats
      - trips
      - files
    ports:
      - '8080:80'
    restart: unless-stopped
    volumes:
      - ./.nginx:/etc/nginx:row

  api-gateway:
    <<: *base-microservice
    build:
      args:
        APP_NAME: api-gateway

  auth:
    <<: *base-microservice
    build:
      args:
        APP_NAME: auth
  users:
    <<: *base-microservice
    build:
      args:
        APP_NAME: users

  locations:
    <<: *base-microservice
    build:
      args:
        APP_NAME: locations
    depends_on:
      - mongo

  trips:
    <<: *base-microservice
    build:
      args:
        APP_NAME: trips
    depends_on:
      - mongo

  files:
    <<: *base-microservice
    build:
      args:
        APP_NAME: files

  chats:
    <<: *base-microservice
    build:
      args:
        APP_NAME: chats
