name: diplomski

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nginx

  auth:
    build:
      args:
        APP_NAME: auth
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh -c "pnpm run prisma:generate && pnpm run start:dev auth"
    container_name: auth
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - postgres
      - rabbitmq
      - nginx

  users:
    build:
      args:
        APP_NAME: users
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh -c "pnpm run prisma:generate && pnpm run start:dev users"
    container_name: users
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mongo
      - postgres
      - rabbitmq
      - nginx

  posts:
    build:
      args:
        APP_NAME: posts
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh -c "pnpm run prisma:generate && pnpm run start:dev posts"
    container_name: posts
    restart: always
    depends_on:
      - postgres
      - mongo
      - rabbitmq
    env_file:
      - .local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mongo
      - postgres
      - rabbitmq
      - nginx

  files:
    build:
      args:
        APP_NAME: files
      context: .
      dockerfile: Dockerfile
      target: build
    command: sh -c "pnpm run prisma:generate && pnpm run start:dev files"
    container_name: files
    restart: always
    depends_on:
      - mongo
    env_file:
      - .local.env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mongo
      - nginx

  rabbitmq:
    image: rabbitmq
    networks:
      - rabbitmq

  redis:
    image: redis:latest
    restart: always

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: example
      POSTGRES_DB: diplomski
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  mongo:
    image: mongo
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: diplomski
    # MONGO_INITDB_ROOT_PASSWORD: example
    # MONGO_INITDB_DATABASE: diplomski
    volumes:
      - mongo:/data/db
    networks:
      - mongo

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - '28081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      # ME_CONFIG_MONGODB_AUTH_USERNAME: diplomski
      # ME_CONFIG_MONGODB_AUTH_PASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: changeme
      ME_CONFIG_OPTIONS_EDITORTHEME: shadowfox
    depends_on:
      - mongo
    networks:
      - mongo

volumes:
  postgres:
    name: postgres-db
  mongo:
    name: mongo-db

networks:
  rabbitmq:
  postgres:
  mongo:
  nginx:
