name: diplomski

include:
  - path:
      - docker-compose.base.yml

x-base-microservice: &base-microservice
  build:
    context: .
    dockerfile: Dockerfile
  ports:
    - '3000'
  restart: unless-stopped
  depends_on:
    - postgres
  env_file:
    - .env

services:
  api-gateway:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/api-gateway/production
    build:
      args:
        APP_NAME: api-gateway

  auth:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/auth/production
    build:
      args:
        APP_NAME: auth
  users:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/users/production
    build:
      args:
        APP_NAME: users

  locations:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/locations/production
    build:
      args:
        APP_NAME: locations
    depends_on:
      - mongo

  trips:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/trips/production
    build:
      args:
        APP_NAME: trips
    depends_on:
      - mongo

  files:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/files/production
    build:
      args:
        APP_NAME: files

  chats:
    <<: *base-microservice
    image: europe-central2-docker.pkg.dev/diplomski-431623/chats/production
    build:
      args:
        APP_NAME: chats
