apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: mongo
  name: mongo
data:
  ME_CONFIG_MONGODB_SERVER: mongo-service
  # ME_CONFIG_MONGODB_PORT: 27017
  # ME_CONFIG_MONGODB_AUTH_DATABASE: admin
  # ME_CONFIG_MONGODB_AUTH_USERNAME: diplomski
  # ME_CONFIG_MONGODB_AUTH_PASSWORD: example
  ME_CONFIG_BASICAUTH_USERNAME: admin
  ME_CONFIG_BASICAUTH_PASSWORD: changeme
  ME_CONFIG_OPTIONS_EDITORTHEME: shadowfox