apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  selector:
    app: redis
  ports:
    - name: '6379'
      port: 6379
      protocol: TCP
      targetPort: 6379
  type: NodePort
