apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: '3001'
      port: 3001
      protocol: TCP
      targetPort: 3001
  type: NodePort
