apiVersion: v1
kind: Service
metadata:
  labels:
    app: locations
  name: locations
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: locations
  type: NodePort
