apiVersion: v1
kind: Service
metadata:
  labels:
    app: locations
  name: locations
spec:
  selector:
    app: locations
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
