apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: files
  name: files
spec:
  replicas: 1
  selector:
    matchLabels:
      app: files
  template:
    metadata:
      labels:
        app: files
    spec:
      containers:
        - name: files
          image: europe-central2-docker.pkg.dev/diplomski-431623/files/production
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: files
          ports:
            - containerPort: 3000
