apiVersion: v1
kind: Service
metadata:
  labels:
    app: files
  name: files
spec:
  selector:
    app: files
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
