apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: europe-central2-docker.pkg.dev/diplomski-431623/users/production
          name: users
          env:
            - name: HTTP_PORT
              value: '3000'
          ports:
            - containerPort: 3000
