apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users
spec:
  selector:
    app: users
  ports:
    - name: '3000'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
