apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
  name: users
spec:
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: users
  type: NodePort
