apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: api-gateway
  name: api-gateway
data:
  HTTP_PROTOCOL: "http"
  HTTP_PORT: "3000"
  HOSTNAME: "diplomski.test"
  AUTH_HOST: "auth"
  AUTH_PORT: "3000"